"""empty message

Revision ID: 8a2e56498918
Revises:
Create Date: 2023-06-14 12:55:48.651722

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '8a2e56498918'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.Column('quote', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('instagram', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=40), nullable=True),
    sa.Column('artist_image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('art_pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('art_image_url', sa.String(length=500), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist_items',
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('wishlist_user_id', sa.Integer(), nullable=True),
    sa.Column('wishlist_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wishlist_item_id'], ['art_pieces.id'], ),
    sa.ForeignKeyConstraint(['wishlist_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('wishlist_id')
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE art_pieces SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE wishlist_items SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_items')
    op.drop_table('art_pieces')
    op.drop_table('users')
    # ### end Alembic commands ###
